
version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  btd:
    jobs:
      - orb-tools/publish:
          orb-path: orb/deployhub-orb.yml
          orb-ref: deployhub/deployhub-orb@dev:1.0.0
          publish-token-variable: "$CIRCLECI_DEV_API_TOKEN"
          validate: true
